packages:
  - ./
  - playground/

allowUnusedPatches: true

catalog:
  '@alanscodelog/commitlint-config': ^3.1.2
  '@alanscodelog/eslint-config': ^6.3.1
  '@alanscodelog/semantic-release-config': ^6.0.2
  '@alanscodelog/tsconfigs': ^6.3.0
  '@alanscodelog/utils': ^6.2.0
  '@alanscodelog/vite-config': ^0.0.7
  '@commitlint/cli': ^20.5.0
  '@iconify/json': ^2.2.458
  '@nuxt/eslint-config': ^1.15.2
  '@nuxt/kit': ^4.4.2
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.4.2
  '@nuxt/types': ^2.18.1
  '@types/node': ^25.5.2
  '@vitejs/plugin-vue': ^6.0.5
  '@vitest/coverage-c8': ^0.33.0
  '@witchcraft/expressit': ^0.4.2
  '@witchcraft/ui': 0.4.0-beta.11
  concurrently: ^9.2.1
  cross-env: ^10.1.0
  defu: ^6.1.6
  fast-glob: ^3.3.3
  http-server: ^14.1.1
  husky: ^9.1.7
  indexit: 2.1.0-beta.3
  madge: ^8.0.0
  nuxt: ^4.4.2
  onchange: ^7.1.0
  reka-ui: ^2.9.3
  semantic-release: ^25.0.3
  tailwindcss: ^4.2.2
  typedoc: 0.28.18
  typescript: ^6.0.2
  unbuild: ^3.6.1
  unplugin-icons: ^23.0.1
  vite-tsconfig-paths: ^6.1.1
  vitest: ^4.1.2
  vue: ^3.5.32
  vue-tsc: ^3.2.6

patchedDependencies:
  '@nuxt/module-builder': patches/@nuxt__module-builder.patch

settings:
  catalogMode: strict
  cleanupUnusedCatalogs: false
