name: Docs

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ docs ]

jobs:
  docs:
    if: "vars.ENABLE_DOCS == 'true'"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*"]
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: alanscodelog/actions/.github/actions/setup@master
        with:
          USE_LOCKFILE: ${{ vars.USE_LOCKFILE }}

      - name: Build
        uses: alanscodelog/actions/.github/actions/build@master

      - name: Deploy Docs
        uses: alanscodelog/actions/.github/actions/docs@master
        with:
          build_playground: true
          build_demo: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}