name: Release

env:
  USE_LOCKFILE: ${{ secrets.USE_LOCKFILE }}
  ENABLE_RELEASE: ${{ secrets.ENABLE_RELEASE }}

on:
  push:
    branches: [ master, alpha, beta, build ]
  repository_dispatch:
    types: [ release ]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*"]

    steps:
    - uses: actions/checkout@v4

    - name: Setup
      uses: ./.github/actions/composite-setup
      with:
        USE_LOCKFILE: ${{ secrets.USE_LOCKFILE }}

      # this is a special case
      # builds needs to be avail for the playground
      # when it links since we use the package directly in it
    - run: pnpm nuxt prepare && pnpm build:only

    - run: pnpm i --frozen-lockfile
      working-directory: playground 

    - run: cat node_modules/@witchcraft/spellcraft/package.json 
      working-directory: playground  

    - name: Build 
      uses: ./.github/actions/composite-build
      with:
        USE_LOCKFILE: ${{ secrets.USE_LOCKFILE }}

    - name: Release
      if: "env.ENABLE_RELEASE == 'true' && ! contains('refs/heads/build ', github.ref)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: pnpm semantic-release

    - name: Release Dry Run
      if: "env.ENABLE_RELEASE != 'true' || contains('refs/heads/build ', github.ref)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: pnpm semantic-release --dry-run 

    - run: echo "env.ENABLE_RELEASE is ${{ env.ENABLE_RELEASE == 'true' }} and branch is ${{ github.ref }}, no release can be published." && exit 1
      if: "env.ENABLE_RELEASE != 'true' || contains('refs/heads/build ', github.ref)"
